You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.

Write a function that returns the letter that was added to str_2.

Examples:

csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"
Notes:

str_1 and str_2 both consist of only lowercase alpha characters.

"""
Understand:
- we have two strings with identical content
- str_2 is shuffled and a random letter is added
- determine the added letter

Plan:
sort str_1
sort str_2
iterate through str_1 at index i
    if str_1 at index i DOES NOT EQUAL str_2 at index i
return str_2
"""
def csFindAddedLetter(str_1, str_2):
    str_a = sorted(str_1)
    str_b = sorted(str_2)

    for i in range(len(str_a)):
        if str_a[i] != str_b[i]:
            return str_b[i]
    return str_b[len(str_b)-1]
